### ISSUE TITLE
Compile OpenWRT's chipstack project report unrecognized command line option '- m64'

### ISSUE THREAD

**Issue by zyphxy** [chirpstack/chirpstack-openwrt-feed#13]
Hello, I am compiling the chipstack project for OpenWRT and I would like to compile it to the gateway of OpenWRT's MIPS architecture. However, the result is' unrecognized command line option '- m64'. Do you know how to solve this problem？

Error log：
taging_dir/target-mipsel_24kc_musl/host/include -c
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/d1_lib.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o] Error 1
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/d1_msg.o] Error 1
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/d1_srtp.o] Error 1
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
mipsel-linux-musl-gcc: error: unrecognized command-line option '-m64'
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/packet.o] Error 1
make[4]: *** [deps/openssl/openssl.target.mk:873: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/methods.o] Error 1
make[3]: *** [Makefile:109: node] Error 2
make[3]: Leaving directory '/home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3'
make[2]: *** [Makefile:161: /home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/build_dir/hostpkg/node-v14.21.3/.built] Error 2
make[2]: Leaving directory '/home/yupeng/openwrt/openwrt-21.02/gateway_openwrt_allv3/feeds/packages/lang/node'
time: package/feeds/packages/node/host-compile#11.37#1.63#6.20
    ERROR: package/feeds/packages/node [host] failed to build.

**Comment by brocaar** [comment]
I don't know what the error means. You can find instructions to setup a working environment here:
https://github.com/chirpstack/chirpstack-gateway-os.

**Comment by zyphxy** [comment]
Okay, let me take a look
