### ISSUE TITLE
Compile Rust Error

### ISSUE THREAD

**Issue by liyajie888** [chirpstack/chirpstack-openwrt-feed#4]
Hi All:
I am using Docker to cross compile  chipstack Package, i choose chirpstack in menuconfig ,when compiling to rust, rust keeps reporting errors:

Couldn't find libc.a in musl libdir:/data/openwrt23/staging_dir/toolchain lipsel openwrt Linux musl/lib

This is my compilation log：

make[3]: Entering directory '/data/openwrt23/feeds/packages/lang/rust'
. /data/openwrt23/include/shell.sh; xzcat /docker_share/openwrt_dl/rustc-1.76.0-src.tar.xz | tar -C /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src

Applying ./patches/0001-Update-xz2-and-use-it-static.patch using plaintext:
patching file src/bootstrap/Cargo.lock
patching file src/bootstrap/Cargo.toml

Applying ./patches/0002-rustc-bootstrap-cache.patch using plaintext:
patching file src/bootstrap/bootstrap.py
patching file src/bootstrap/src/core/download.rs

Applying ./patches/0003-bump-libc-deps-to-0.2.146.patch using plaintext:
patching file vendor/addr2line-0.19.0/Cargo.lock
patching file vendor/backtrace-0.3.67/Cargo.lock
patching file vendor/crossbeam-channel/Cargo.lock
patching file vendor/elasticlunr-rs/Cargo.lock
patching file vendor/handlebars/Cargo.lock
patching file vendor/libffi/Cargo.lock
touch /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/.preparedd8397be96c0c5f15129d4052b03290a3_6664517399ebbbc92a37c5bb081b5c53
(cd /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/; if [ -x configure ]; then cp -fpR /data/openwrt23/scripts/config.{guess,sub} /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src// && CC="gcc" CFLAGS="-O2 -I/data/openwrt23/staging_dir/host/include -I/data/openwrt23/staging_dir/hostpkg/include -I/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/include" CXX="g++" CPPFLAGS="-I/data/openwrt23/staging_dir/host/include -I/data/openwrt23/staging_dir/hostpkg/include -I/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/include" CXXFLAGS="" LDFLAGS="-L/data/openwrt23/staging_dir/host/lib -L/data/openwrt23/staging_dir/hostpkg/lib -L/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/lib" CONFIG_SHELL="/usr/bin/env bash" CARGO_HOME="/docker_share/openwrt_dl/cargo" bash ./configure --build=x86_64-unknown-linux-gnu --target=mipsel-unknown-linux-musl,x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu --prefix=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host --bindir=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/bin --libdir=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/lib --sysconfdir=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/etc --datadir=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/share --mandir=/data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/host/man --dist-compression-formats=gz --enable-missing-tools --disable-sanitizers --release-channel=stable --enable-cargo-native-static --set=llvm.download-ci-llvm=true --set=target.mipsel-unknown-linux-musl.ar=mipsel-openwrt-linux-musl-gcc-ar --set=target.mipsel-unknown-linux-musl.cc=mipsel-openwrt-linux-musl-gcc --set=target.mipsel-unknown-linux-musl.cxx=mipsel-openwrt-linux-musl-g++ --set=target.mipsel-unknown-linux-musl.linker=mipsel-openwrt-linux-musl-gcc --set=target.mipsel-unknown-linux-musl.ranlib=mipsel-openwrt-linux-musl-gcc-ranlib --set=target.mipsel-unknown-linux-musl.crt-static=false --set=target.mipsel-unknown-linux-musl.musl-root=/data/openwrt23/staging_dir/toolchain-mipsel-openwrt-linux-musl ; fi )
configure: processing command line
configure:
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--target ...
configure: build.build := x86_64-unknown-linux-gnu
configure: build.target := ['mipsel-unknown-linux-musl', 'x86_64-unknown- ...
configure: build.host := ['x86_64-unknown-linux-gnu']
configure: install.prefix := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: install.bindir := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: install.libdir := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: install.sysconfdir := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: install.datadir := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: install.mandir := /data/openwrt23/staging_dir/target-mipsel-open ...
configure: dist.compression-formats := ['gz']
configure: dist.missing-tools := True
configure: build.sanitizers := False
configure: rust.channel := stable
configure: build.cargo-native-static := True
configure: llvm.download-ci-llvm := True
configure: target.mipsel-unknown-linux-musl.ar := mipsel-openwrt-linux-musl-gcc-a ...
configure: target.mipsel-unknown-linux-musl.cc := mipsel-openwrt-linux-musl-gcc
configure: target.mipsel-unknown-linux-musl.cxx := mipsel-openwrt-linux-musl-g++
configure: target.mipsel-unknown-linux-musl.linker := mipsel-openwrt-linux-musl-g ...
configure: target.mipsel-unknown-linux-musl.ranlib := mipsel-openwrt-linux-musl-g ...
configure: target.mipsel-unknown-linux-musl.crt-static := False
configure: target.mipsel-unknown-linux-musl.musl-root := /data/openwrt23/staging_ ...
configure: profile := dist
configure:
configure: writing config.toml in current directory
configure:
configure: run python /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/x.py --help
touch /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/.configured
CARGO_HOME=/docker_share/openwrt_dl/cargo TARGET_CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -msoft-float -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" OPENWRT_RUSTC_BOOTSTRAP_CACHE=/docker_share/openwrt_dl/rustc python3 /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/x.py --build-dir /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/build --config /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/config.toml dist build-manifest cargo llvm-tools rustc rust-std rust-src
INFO: looks like you're trying to run this command as root
and so in order to preserve your $HOME this will now
use vendored sources by default.
extracting /docker_share/openwrt_dl/rustc/2023-12-28/rust-std-1.75.0-x86_64-unknown-linux-gnu.tar.xz
extracting /docker_share/openwrt_dl/rustc/2023-12-28/rustc-1.75.0-x86_64-unknown-linux-gnu.tar.xz
extracting /docker_share/openwrt_dl/rustc/2023-12-28/cargo-1.75.0-x86_64-unknown-linux-gnu.tar.xz
Building bootstrap
Compiling proc-macro2 v1.0.60
Compiling memchr v2.5.0
Compiling quote v1.0.26
Compiling cfg-if v1.0.0
Compiling unicode-ident v1.0.0
Compiling typenum v1.15.0
Compiling libc v0.2.150
Compiling version_check v0.9.4
Compiling generic-array v0.14.5
Compiling cc v1.0.73
Compiling serde v1.0.160
Compiling log v0.4.17
Compiling lazy_static v1.4.0
Compiling syn v2.0.8
Compiling pkg-config v0.3.25
Compiling regex-automata v0.1.10
Compiling aho-corasick v0.7.18
Compiling bstr v0.2.17
Compiling lzma-sys v0.1.20
Compiling rustix v0.38.19
Compiling crossbeam-utils v0.8.14
Compiling serde_derive v1.0.160
Compiling regex-syntax v0.6.26
Compiling heck v0.4.1
Compiling anstyle v1.0.0
Compiling clap_lex v0.6.0
Compiling clap_builder v4.4.7
Compiling block-buffer v0.10.2
Compiling crypto-common v0.1.3
Compiling fnv v1.0.7
Compiling same-file v1.0.6
Compiling bitflags v2.4.1
Compiling semver v1.0.17
Compiling serde_json v1.0.81
Compiling once_cell v1.12.0
Compiling linux-raw-sys v0.4.10
Compiling regex v1.5.6
Compiling clap_derive v4.4.7
Compiling globset v0.4.8
Compiling thread_local v1.1.4
Compiling walkdir v2.3.2
Compiling digest v0.10.3
Compiling xattr v0.2.3
Compiling filetime v0.2.16
Compiling ryu v1.0.10
Compiling itoa v1.0.2
Compiling cpufeatures v0.2.5
Compiling bootstrap v0.0.0 (/data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/src/bootstrap)
Compiling sha2 v0.10.2
Compiling ignore v0.4.18
Compiling tar v0.4.38
Compiling clap v4.4.7
Compiling clap_complete v4.4.3
Compiling fd-lock v3.0.13
Compiling toml v0.5.9
Compiling opener v0.5.0
Compiling object v0.32.0
Compiling cmake v0.1.48
Compiling home v0.5.4
Compiling xz2 v0.1.7
Compiling termcolor v1.2.0
Compiling build_helper v0.1.0 (/data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/src/tools/build_helper)
Finished dev [unoptimized] target(s) in 1m 52s
WARNING: The change-id is missing in the config.toml. This means that you will not be able to track the major changes made to the bootstrap configurations.
NOTE: to silence this warning, add change-id = 118703 at the top of config.toml
thread 'main' panicked at src/core/sanity.rs:229:25:
couldn't find libc.a in musl libdir: /data/openwrt23/staging_dir/toolchain-mipsel-openwrt-linux-musl/lib
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Build completed unsuccessfully in 0:03:39
make[3]: *** [Makefile:110: /data/openwrt23/build_dir/target-mipsel-openwrt-linux-musl_musl/host/rustc-1.76.0-src/.built] Error 1
make[3]: Leaving directory '/data/openwrt23/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#237.49#1789.45#1862.32
ERROR: package/feeds/packages/rust [host] failed to build.
make[2]: *** [package/Makefile:126: package/feeds/packages/rust/host/compile] Error 1
make[2]: Leaving directory '/data/openwrt23'
make[1]: *** [package/Makefile:122: /data/openwrt23/staging_dir/target-mipsel-openwrt-linux-musl_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/data/openwrt23'
make: *** [/data/openwrt23/include/toplevel.mk:232: world] Error 2

Help me check what the problem is, thank you！

**Comment by brocaar** [comment]
Please find a complete OpenWrt environment setup with this feed here:
https://github.com/chirpstack/chirpstack-gateway-os

**Comment by liyajie888** [comment]
Hi brocaar:
 Thanks your reply,i has slove this issue,i have successfully cross compile rust .In the subsequent cross compilation, I still used the official openwrt23.05 SDK ,and add this feeds,my target plantform architecture is MIP,and have encountered another issue as follows:

 Compiling p12 v0.6.3
     Running `rustc --crate-name p12 --edition=2021 /docker_share/openwrt_dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/p12-0.6.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=163 --crate-type lib --emit=dep-info,metadata,link -C opt-level=z -C linker-plugin-lto -C codegen-units=1 -C overflow-checks=on -C metadata=715b85bb4a4230ad -C extra-filename=-715b85bb4a4230ad --out-dir /data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps --target mipsel-unknown-linux-musl -C linker=mipsel-openwrt-linux-musl-gcc -L dependency=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps -L dependency=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/deps --extern cbc=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libcbc-dc83b88dca7856e6.rmeta --extern cipher=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libcipher-b1f3743065bae7ba.rmeta --extern des=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libdes-8efb7e335d275f50.rmeta --extern getrandom=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libgetrandom-960e77d6e5aad186.rmeta --extern hmac=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libhmac-da985b574210a4d9.rmeta --extern lazy_static=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/liblazy_static-4703929b8389f168.rmeta --extern rc2=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/librc2-c20908f7eae2424a.rmeta --extern sha1=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libsha1-77bdd0fbd5d6420e.rmeta --extern yasna=/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/mipsel-unknown-linux-musl/release/deps/libyasna-01cea9d6e038af45.rmeta --cap-lints allow -Ctarget-feature=-crt-static -lssp_nonshared -latomic`
     Running `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/build/num-iter-e08e7a29ff1844bd/build-script-build`
     Running `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/build/polling-313088607840c8a9/build-script-build`
     Running `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/build/bigdecimal-c37b9084f34c5ebf/build-script-build`
     Running `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/build/ring-337be7f56a149ea7/build-script-build`
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target/release/build/ring-337be7f56a149ea7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /docker_share/openwrt_dl/cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `chirpstack v4.6.0 (/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/chirpstack)`, intermediate artifacts can be found at `/data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
make[3]: *** [Makefile:83: /data/openwrt23/build_dir/target-mipsel_24kc_musl/chirpstack-4.6.0/.built] Error 101
make[3]: Leaving directory '/data/openwrt23/feeds/chirpstack/chirpstack/chirpstack'
time: package/feeds/chirpstack/chirpstack/compile#349.85#98.28#811.32
    ERROR: package/feeds/chirpstack/chirpstack failed to build.
make[2]: *** [package/Makefile:128: package/feeds/chirpstack/chirpstack/compile] Error 1
make[2]: Leaving directory '/data/openwrt23'
make[1]: *** [package/Makefile:122: /data/openwrt23/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/data/openwrt23'
make: *** [/data/openwrt23/include/toplevel.mk:232: world] Error 2

So, can you tell me the reason for this problem.Thank you again!

**Comment by brocaar** [comment]
I have never tried compiling the `chirpstack` package to MIPS. Are you sure it is powerful enough for ChirpStack + PostgreSQL + Redis + Mosquitto?

Initially I did have issues when compiling ChirpStack MQTT Forwarder to MIPS. This was because `ring` didn't have support yet for `mips` targets, please see:

https://github.com/briansmith/ring/issues/1866

Looking at the version that fails to build, this is probably the cause.

**Comment by bulutbekdemir** [comment]
Hi,
 We are using Ubuntu 22.04.4 LTS to compile, we compiled openwrt successfully before on this machine and configuration. We wanted to use some of the chirpstack components on our project and started building but we also faced the same issue, we also tried to disable it but it also resulted in a different error.
 
 Also, we have seen some topics about different sites(forum.openwrt.org, another GitHub issue/wikis, etc.) but we really didn't find a solution for our problem.
 
How did you solve the issue @liyajie888  ?
Also if you @brocaar  explain some details to us for solving this problem this would be perfect.
 
 ```
 SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/linux-firmware-20230804/.pkgdir/brcmfmac-nvram-43455-sdio/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.brcmfmac-nvram-43455-sdio_installed
echo "brcmfmac-nvram-43455-sdio" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/linux-firmware.default.install
mkdir -p /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp
curl: (22) The requested URL returned error: 404                              

SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/linux-firmware-20230804/.pkgdir/brcmfmac-firmware-usb/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
error: failed to download llvm from ci

    help: old builds get deleted after a certain time
    help: if trying to compile an old commit of rustc, disable download-ci-llvm in config.toml:

    [llvm]
    download-ci-llvm = false
    
Build completed unsuccessfully in 0:00:03
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.brcmfmac-firmware-usb_installed
echo "brcmfmac-firmware-usb" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/linux-firmware.default.install
mkdir -p /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp
SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/linux-firmware-20230804/.pkgdir/r8169-firmware/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
make[3]: * [Makefile:110: /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/host/rustc-1.73.0-src/.built] Error 1
make[3]: Leaving directory '/home/ksp/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#2.24#1.72#4.15
    ERROR: package/feeds/packages/rust [host] failed to build.
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.r8169-firmware_installed
make[2]: * [package/Makefile:126: package/feeds/packages/rust/host/compile] Error 1
make[2]: * Waiting for unfinished jobs....
echo "r8169-firmware" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/linux-firmware.default.install
make[3]: Leaving directory '/home/ksp/openwrt/package/firmware/linux-firmware'
time: package/firmware/linux-firmware/compile#1.35#0.09#1.42
mkdir -p /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp
SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/luci-lib-ip/.pkgdir/luci-lib-ip/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.luci-lib-ip_installed
echo "luci-lib-ip" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/luci-lib-ip.default.install
make[3]: Leaving directory '/home/ksp/openwrt/feeds/luci/libs/luci-lib-ip'
time: package/feeds/luci/luci-lib-ip/compile#0.78#0.07#0.84
mkdir -p /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp
SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/luci-lib-jsonc/.pkgdir/luci-lib-jsonc/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.luci-lib-jsonc_installed
echo "luci-lib-jsonc" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/luci-lib-jsonc.default.install
make[3]: Leaving directory '/home/ksp/openwrt/feeds/luci/libs/luci-lib-jsonc'
time: package/feeds/luci/luci-lib-jsonc/compile#0.77#0.09#0.86
mkdir -p /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp
SHELL= flock /home/ksp/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/ksp/openwrt/build_dir/target-aarch64_cortex-a72_musl/luci-lib-nixio/.pkgdir/luci-lib-nixio/. /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/'
touch /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/root-bcm27xx/stamp/.luci-lib-nixio_installed
echo "luci-lib-nixio" >> /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/pkginfo/luci-lib-nixio.default.install
make[3]: Leaving directory '/home/ksp/openwrt/feeds/luci/libs/luci-lib-nixio'
time: package/feeds/luci/luci-lib-nixio/compile#0.95#0.11#1.05
make[2]: Leaving directory '/home/ksp/openwrt'
make[1]: * [package/Makefile:122: /home/ksp/openwrt/staging_dir/target-aarch64_cortex-a72_musl/stamp/.package_compile] Error 2
make[1]: * Waiting for unfinished jobs....
make[2]: Leaving directory '/home/ksp/openwrt'
make[1]: Leaving directory '/home/ksp/openwrt'
make: * [/home/ksp/openwrt/include/toplevel.mk:232: world] Error 2

```
